# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77146a520332f9da162bec0b6501fc043012e0cf2518df6cf3b6d1ebeaeacd56ee117f1cc885ce69f75e016ba3656576c348a70e9efc48a06758a8f54731aba4

test:
  secret_key_base: ce820c3fe186c34079077ee6c58b482ddb43cba766ad28bfd03b9582a6ce7885f2d33c137bcfe384f38e447cde16ab0e1a28a0b06fda24ab957bd3158023f034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
